insert into vigia values ('Albergaria-a-Velha', 67);
insert into vigia values ('Valpacos', 107);
insert into vigia values ('Aljustrel', 32);
insert into vigia values ('Sao Pedro do Sul', 151);
insert into vigia values ('Castro Daire', 15);
insert into vigia values ('Batalha', 180);
insert into vigia values ('Torres Vedras', 26);
insert into vigia values ('Sesimbra', 13);
insert into vigia values ('Tondela', 220);
insert into vigia values ('Amares', 172);
insert into vigia values ('Penacova', 224);
insert into vigia values ('Santarem', 131);
insert into vigia values ('Caldas da Rainha', 90);
insert into vigia values ('Vila Real', 116);
insert into vigia values ('Vila Flor', 157);
insert into vigia values ('Castanheira de Pera', 223);
insert into vigia values ('Lourinha', 200);
insert into vigia values ('Mira', 256);
insert into vigia values ('Gondomar', 108);
insert into vigia values ('Felgueiras', 44);
insert into vigia values ('Odivelas', 262);
insert into vigia values ('Odemira', 137);
insert into vigia values ('Vila Nova de Cerveira', 275);
insert into vigia values ('Penedono', 203);
insert into vigia values ('Vila Nova de Paiva', 40);
insert into vigia values ('Sever do Vouga', 35);
insert into vigia values ('Vila Nova de Poiares', 227);
insert into vigia values ('Evora', 216);
insert into vigia values ('Marvao', 257);
insert into vigia values ('Lousada', 56);
insert into vigia values ('Crato', 99);
insert into vigia values ('Campo Maior', 121);
insert into vigia values ('Caminha', 194);
insert into vigia values ('Moita', 235);
insert into vigia values ('Penafiel', 197);
insert into vigia values ('Amarante', 10);
insert into vigia values ('Nelas', 46);
insert into vigia values ('Alandroal', 2);
insert into vigia values ('Montemor-o-Velho', 62);
insert into vigia values ('Cartaxo', 241);
insert into vigia values ('Espinho', 50);
insert into vigia values ('Coruche', 208);
insert into vigia values ('Moncao', 49);
insert into vigia values ('Mondim de Basto', 177);
insert into vigia values ('Santa Marta de Penaguiao', 187);
insert into vigia values ('Santa Cruz', 189);
insert into vigia values ('Terras de Bouro', 211);
insert into vigia values ('Cuba', 7);
insert into vigia values ('Alfandega da Fe', 254);
insert into vigia values ('Vila Nova de Foz Coa', 160);
insert into vigia values ('Matosinhos', 70);
insert into vigia values ('Cascais', 249);
insert into vigia values ('Figueira de Castelo Rodrigo', 36);
insert into vigia values ('Monchique', 155);
insert into vigia values ('Ribeira de Pena', 135);
insert into vigia values ('Serta', 88);
insert into vigia values ('Calheta', 273);
insert into vigia values ('Vila Velha de Rodao', 153);
insert into vigia values ('Sabugal', 167);
insert into vigia values ('Santa Comba Dao', 85);
insert into vigia values ('Guimaraes', 175);
insert into vigia values ('Condeixa-a-Nova', 231);
insert into vigia values ('Ourem', 127);
insert into vigia values ('Loule', 120);
insert into vigia values ('Ponte da Barca', 138);
insert into vigia values ('Montemor-o-Novo', 158);
insert into vigia values ('Grandola', 261);
insert into vigia values ('Abrantes', 148);
insert into vigia values ('Castelo de Paiva', 174);
insert into vigia values ('Sao Joao da Pesqueira', 8);
insert into vigia values ('Almeirim', 19);
insert into vigia values ('Seia', 246);
insert into vigia values ('Marinha Grande', 259);
insert into vigia values ('Figueira da Foz', 205);
insert into vigia values ('Freixo de Espada a Cinta', 118);
insert into vigia values ('Tavira', 201);
insert into vigia values ('Vimioso', 145);
insert into vigia values ('Baiao', 91);
insert into vigia values ('Mourao', 61);
insert into vigia values ('Chaves', 210);
insert into vigia values ('Porto de Mos', 22);
insert into vigia values ('Vidigueira', 0);
insert into vigia values ('Povoa de Lanhoso', 17);
insert into vigia values ('Sao Vicente', 181);
insert into vigia values ('Madalena', 154);
insert into vigia values ('Oeiras', 81);
insert into vigia values ('Porto Moniz', 242);
insert into vigia values ('Vila Franca de Xira', 250);
insert into vigia values ('Sintra', 168);
insert into vigia values ('Castelo Branco', 232);
insert into vigia values ('Anadia', 110);
insert into vigia values ('Leiria', 228);
insert into vigia values ('Camara de Lobos', 51);
insert into vigia values ('Satao', 190);
insert into vigia values ('Almeida', 84);
insert into vigia values ('Santo Tirso', 240);
insert into vigia values ('Oliveira do Hospital', 72);
insert into vigia values ('Vila Nova da Barquinha', 199);
insert into vigia values ('Chamusca', 270);
insert into vigia values ('Viseu', 24);
insert into vigia values ('Mertola', 233);
insert into vigia values ('Almodovar', 29);
insert into vigia values ('Esposende', 83);
insert into vigia values ('Manteigas', 98);
insert into vigia values ('Alvito', 4);
insert into vigia values ('Castro Verde', 133);
insert into vigia values ('Portel', 159);
insert into vigia values ('Oleiros', 143);
insert into vigia values ('Vouzela', 124);
insert into vigia values ('Alcoutim', 202);
insert into vigia values ('Penamacor', 60);
insert into vigia values ('Mogadouro', 58);
insert into vigia values ('Oliveira do Bairro', 213);
insert into vigia values ('Mealhada', 18);
insert into vigia values ('Pacos de Ferreira', 73);
insert into vigia values ('Castelo de Vide', 225);
insert into vigia values ('Tabua', 237);
insert into vigia values ('Meda', 134);
insert into vigia values ('Santa Maria da Feira', 221);
insert into vigia values ('Ponte de Lima', 75);
insert into vigia values ('Paredes de Coura', 104);
insert into vigia values ('Gouveia', 102);
insert into vigia values ('Miranda do Douro', 272);
insert into vigia values ('Ferreira do Zezere', 193);
insert into vigia values ('Obidos', 162);
insert into vigia values ('Ribeira Brava', 182);
insert into vigia values ('Gaviao', 217);
insert into vigia values ('Vagos', 183);
insert into vigia values ('Benavente', 25);
insert into vigia values ('Melgaco', 95);
insert into vigia values ('Vila Vicosa', 114);

insert into eventoEmergencia  values (920000000, '2017-09-01 13:07:07', 'Rita Oliveira', 'Albergaria-a-Velha', 0);
insert into eventoEmergencia  values (920000001, '2017-10-24 14:59:53', 'Catarina Dias', 'Proenca-a-Nova', 1);
insert into eventoEmergencia  values (920000002, '2018-10-25 22:45:48', 'Catarina Mesquita', 'Valpacos', 2);
insert into eventoEmergencia  values (920000003, '2017-08-28 07:17:56', 'Diogo Mota', 'Aljustrel', 3);
insert into eventoEmergencia  values (920000004, '2018-08-29 04:31:25', 'Helena Marante', 'Sao Pedro do Sul', 4);
insert into eventoEmergencia  values (920000005, '2018-07-08 03:06:00', 'Joao Marante', 'Castro Daire', 5);
insert into eventoEmergencia  values (920000006, '2017-09-19 11:12:16', 'Helena Mota', 'Batalha', 6);
insert into eventoEmergencia  values (920000007, '2017-10-23 01:45:44', 'Joao Barata', 'Torres Vedras', 7);
insert into eventoEmergencia  values (920000008, '2017-06-19 01:03:30', 'Rita Dias', 'Sesimbra', 8);
insert into eventoEmergencia  values (920000009, '2017-10-27 16:59:52', 'Miguel Baltazar', 'Tondela', 9);
insert into eventoEmergencia  values (920000010, '2017-07-10 02:48:37', 'Helena Baltazar', 'Vila Verde', 10);
insert into eventoEmergencia  values (920000011, '2017-05-03 14:22:24', 'Rita Mota', 'Amares', 11);
insert into eventoEmergencia  values (920000012, '2017-10-22 15:49:41', 'Miguel Mesquita', 'Ferreira do Alentejo', 12);
insert into eventoEmergencia  values (920000013, '2017-02-18 11:07:11', 'Rita Silva', 'Penacova', 13);
insert into eventoEmergencia  values (920000014, '2018-05-23 11:39:13', 'Diogo Oliveira', 'Salvaterra de Magos', 14);
insert into eventoEmergencia  values (920000015, '2018-10-08 05:54:19', 'Ana Marante', 'Santarem', 15);
insert into eventoEmergencia  values (920000016, '2017-08-21 07:07:37', 'Diogo Baltazar', 'Alenquer', 16);
insert into eventoEmergencia  values (920000017, '2017-02-26 02:16:00', 'Miguel Dias', 'Caldas da Rainha', 17);
insert into eventoEmergencia  values (920000018, '2017-02-23 11:15:05', 'Diogo Santos', 'Vila Real', 18);
insert into eventoEmergencia  values (920000019, '2018-06-09 19:58:24', 'Ana Silva', 'Boticas', 19);
insert into eventoEmergencia  values (920000020, '2018-10-14 05:11:46', 'Ana Ferreira', 'Vila Flor', 20);
insert into eventoEmergencia  values (920000021, '2017-03-26 05:03:44', 'Helena Mesquita', 'Velas', 21);
insert into eventoEmergencia  values (920000022, '2018-07-21 04:03:45', 'Ana Mota', 'Sardoal', 22);
insert into eventoEmergencia  values (920000023, '2018-08-06 06:26:08', 'Tiago Silva', 'Castanheira de Pera', 23);
insert into eventoEmergencia  values (920000024, '2018-09-01 20:28:06', 'Catarina Barata', 'Celorico de Basto', 24);
insert into eventoEmergencia  values (920000025, '2017-08-23 07:24:07', 'Catarina Ferreira', 'Belmonte', 25);
insert into eventoEmergencia  values (920000026, '2018-01-03 11:18:49', 'Joao Mota', 'Almada', 26);
insert into eventoEmergencia  values (920000027, '2017-06-08 10:37:56', 'Daniel Dias', 'Lourinha', 27);
insert into eventoEmergencia  values (920000028, '2017-12-06 12:43:41', 'Rita Marante', 'Vila do Porto', 28);
insert into eventoEmergencia  values (920000029, '2017-05-18 16:37:21', 'Diogo Baltazar', 'Mira', 29);
insert into eventoEmergencia  values (920000030, '2017-09-26 11:28:30', 'Daniel Barata', 'Povoa de Varzim', 30);
insert into eventoEmergencia  values (920000031, '2017-10-11 03:35:11', 'Miguel Baltazar', 'Moura', 31);
insert into eventoEmergencia  values (920000032, '2018-02-15 03:16:27', 'Helena Dias', 'Vila Nova de Famalicao', 32);
insert into eventoEmergencia  values (920000033, '2018-02-05 15:13:20', 'Catarina Santos', 'Nisa', 33);
insert into eventoEmergencia  values (920000034, '2017-08-06 22:48:08', 'Tiago Mesquita', 'Gondomar', 34);
insert into eventoEmergencia  values (920000035, '2018-04-15 02:05:56', 'Catarina Ferreira', 'Viana do Castelo', 35);
insert into eventoEmergencia  values (920000036, '2017-02-19 14:55:44', 'Ana Dias', 'Felgueiras', 36);
insert into eventoEmergencia  values (920000037, '2017-06-06 14:45:02', 'Catarina Santos', 'Guarda', 37);
insert into eventoEmergencia  values (920000038, '2017-07-14 22:48:01', 'Catarina Dias', 'Odivelas', 38);
insert into eventoEmergencia  values (920000039, '2018-02-14 10:42:40', 'Miguel Baltazar', 'Odemira', 39);
insert into eventoEmergencia  values (920000040, '2018-04-06 18:33:40', 'Diogo Oliveira', 'Fafe', 40);
insert into eventoEmergencia  values (920000041, '2018-03-08 06:16:17', 'Diogo Baltazar', 'Ourique', 41);
insert into eventoEmergencia  values (920000042, '2018-06-24 18:20:17', 'Daniel Santos', 'Penela', 42);
insert into eventoEmergencia  values (920000043, '2018-10-27 05:49:35', 'Catarina Dias', 'Vila Nova de Cerveira', 43);
insert into eventoEmergencia  values (920000044, '2017-07-01 08:37:47', 'Joao Mesquita', 'Vila Franca do Campo', 44);
insert into eventoEmergencia  values (920000045, '2017-08-20 16:32:00', 'Daniel Baltazar', 'Agueda', 45);
insert into eventoEmergencia  values (920000046, '2017-11-08 05:08:01', 'Miguel Dias', 'Marco de Canaveses', 46);
insert into eventoEmergencia  values (920000047, '2017-02-05 07:43:57', 'Helena Dias', 'Arouca', 47);
insert into eventoEmergencia  values (920000048, '2018-04-12 15:34:18', 'Diogo Silva', 'Penedono', 48);
insert into eventoEmergencia  values (920000049, '2017-04-01 17:49:48', 'Rita Mesquita', 'Vila Nova de Paiva', 49);
insert into eventoEmergencia  values (920000050, '2018-10-20 02:29:43', 'Diogo Silva', 'Trancoso', 50);
insert into eventoEmergencia  values (920000051, '2018-05-28 16:25:57', 'Miguel Baltazar', 'Sever do Vouga', 51);
insert into eventoEmergencia  values (920000052, '2018-10-02 13:32:20', 'Helena Marante', 'Loures', 52);
insert into eventoEmergencia  values (920000053, '2018-11-20 20:02:38', 'Ines Oliveira', 'Cantanhede', 53);
insert into eventoEmergencia  values (920000054, '2018-03-23 20:59:31', 'Miguel Marante', 'Viana do Alentejo', 54);
insert into eventoEmergencia  values (920000055, '2018-03-08 15:06:38', 'Ana Santos', 'Aljezur', 55);
insert into eventoEmergencia  values (920000056, '2018-04-26 18:52:04', 'Tiago Marante', 'Vila Nova de Poiares', 56);
insert into eventoEmergencia  values (920000057, '2017-02-19 14:18:42', 'Miguel Silva', 'Evora', 57);
insert into eventoEmergencia  values (920000058, '2017-10-03 03:24:35', 'Daniel Mesquita', 'Alpiarca', 58);
insert into eventoEmergencia  values (920000059, '2017-09-10 14:38:30', 'Helena Ferreira', 'Marvao', 59);
insert into eventoEmergencia  values (920000060, '2018-08-17 06:58:08', 'Ines Mota', 'Lousada', 60);
insert into eventoEmergencia  values (920000061, '2018-02-19 13:05:13', 'Catarina Baltazar', 'Crato', 61);
insert into eventoEmergencia  values (920000062, '2018-08-08 08:02:18', 'Joao Mesquita', 'Campo Maior', 62);
insert into eventoEmergencia  values (920000063, '2018-08-14 10:22:52', 'Helena Baltazar', 'Vinhais', 63);
insert into eventoEmergencia  values (920000064, '2018-09-03 04:22:50', 'Daniel Santos', 'Caminha', 64);
insert into eventoEmergencia  values (920000065, '2017-05-16 03:23:55', 'Ana Mota', 'Moita', 65);
insert into eventoEmergencia  values (920000066, '2017-11-28 22:12:12', 'Daniel Silva', 'Penafiel', 66);
insert into eventoEmergencia  values (920000067, '2017-02-10 08:30:52', 'Diogo Mota', 'Amarante', 67);
insert into eventoEmergencia  values (920000068, '2018-11-06 06:15:32', 'Tiago Ferreira', 'Nelas', 68);
insert into eventoEmergencia  values (920000069, '2018-06-25 16:01:28', 'Daniel Silva', 'Alandroal', 69);
insert into eventoEmergencia  values (920000070, '2017-10-09 23:12:47', 'Ines Mota', 'Penalva do Castelo', 70);
insert into eventoEmergencia  values (920000071, '2017-04-28 05:36:07', 'Diogo Baltazar', 'Alijo', 71);
insert into eventoEmergencia  values (920000072, '2018-10-01 15:36:26', 'Miguel Marante', 'Cabeceiras de Basto', 72);
insert into eventoEmergencia  values (920000073, '2018-02-11 09:21:18', 'Ana Mesquita', 'Montemor-o-Velho', 73);
insert into eventoEmergencia  values (920000074, '2017-09-29 13:20:06', 'Daniel Silva', 'Cartaxo', 74);
insert into eventoEmergencia  values (920000075, '2017-04-08 23:07:33', 'Ana Ferreira', 'Aveiro', 75);
insert into eventoEmergencia  values (920000076, '2018-04-13 03:17:23', 'Rita Ferreira', 'Vila Real de Santo Antonio', 76);
insert into eventoEmergencia  values (920000077, '2017-04-04 03:34:16', 'Diogo Silva', 'Espinho', 77);
insert into eventoEmergencia  values (920000078, '2018-05-17 17:33:46', 'Joao Marante', 'Barrancos', 78);
insert into eventoEmergencia  values (920000079, '2018-04-26 04:51:48', 'Daniel Santos', 'Coruche', 79);
insert into eventoEmergencia  values (920000080, '2017-09-13 15:40:37', 'Ines Mota', 'Santa Cruz das Flores', 80);
insert into eventoEmergencia  values (920000081, '2018-03-31 02:36:33', 'Rita Mesquita', 'Moncao', 81);
insert into eventoEmergencia  values (920000082, '2017-04-11 07:55:48', 'Daniel Silva', 'Tarouca', 82);
insert into eventoEmergencia  values (920000083, '2018-06-30 13:38:39', 'Daniel Barata', 'Mondim de Basto', 83);
insert into eventoEmergencia  values (920000084, '2017-06-24 23:59:19', 'Ines Mota', 'Santa Marta de Penaguiao', 84);
insert into eventoEmergencia  values (920000085, '2017-08-18 01:00:22', 'Catarina Silva', 'Pampilhosa da Serra', 85);
insert into eventoEmergencia  values (920000086, '2017-07-03 03:31:07', 'Miguel Santos', 'Lagoa', 86);
insert into eventoEmergencia  values (920000087, '2018-06-05 12:01:14', 'Rita Oliveira', 'Santa Cruz', 87);
insert into eventoEmergencia  values (920000088, '2018-07-29 01:31:46', 'Daniel Ferreira', 'Terras de Bouro', 88);
insert into eventoEmergencia  values (920000089, '2017-04-26 06:29:06', 'Miguel Marante', 'Sernancelhe', 89);
insert into eventoEmergencia  values (920000090, '2018-03-06 07:46:24', 'Rita Marante', 'Cuba', 90);
insert into eventoEmergencia  values (920000091, '2018-07-23 12:55:33', 'Joao Santos', 'Alfandega da Fe', 91);
insert into eventoEmergencia  values (920000092, '2017-12-14 02:40:29', 'Miguel Baltazar', 'Ovar', 92);
insert into eventoEmergencia  values (920000093, '2018-10-13 02:51:47', 'Daniel Baltazar', 'Palmela', 93);
insert into eventoEmergencia  values (920000094, '2017-04-28 00:25:06', 'Tiago Ferreira', 'Sobral de Monte Agraco', 94);
insert into eventoEmergencia  values (920000095, '2017-04-23 12:45:54', 'Helena Barata', 'Golega', 95);
insert into eventoEmergencia  values (920000096, '2017-11-11 10:55:43', 'Rita Dias', 'Vieira do Minho', 96);
insert into eventoEmergencia  values (920000097, '2018-09-19 10:29:00', 'Catarina Dias', 'Ansiao', 97);
insert into eventoEmergencia  values (920000098, '2017-02-14 20:04:39', 'Rita Mota', 'Beja', 98);
insert into eventoEmergencia  values (920000099, '2018-08-06 09:17:52', 'Miguel Ferreira', 'Arruda dos Vinhos', 99);

insert into processoSocorro values (0);
insert into processoSocorro values (1);
insert into processoSocorro values (2);
insert into processoSocorro values (3);
insert into processoSocorro values (4);
insert into processoSocorro values (5);
insert into processoSocorro values (6);
insert into processoSocorro values (7);
insert into processoSocorro values (8);
insert into processoSocorro values (9);
insert into processoSocorro values (10);
insert into processoSocorro values (11);
insert into processoSocorro values (12);
insert into processoSocorro values (13);
insert into processoSocorro values (14);
insert into processoSocorro values (15);
insert into processoSocorro values (16);
insert into processoSocorro values (17);
insert into processoSocorro values (18);
insert into processoSocorro values (19);
insert into processoSocorro values (20);
insert into processoSocorro values (21);
insert into processoSocorro values (22);
insert into processoSocorro values (23);
insert into processoSocorro values (24);
insert into processoSocorro values (25);
insert into processoSocorro values (26);
insert into processoSocorro values (27);
insert into processoSocorro values (28);
insert into processoSocorro values (29);
insert into processoSocorro values (30);
insert into processoSocorro values (31);
insert into processoSocorro values (32);
insert into processoSocorro values (33);
insert into processoSocorro values (34);
insert into processoSocorro values (35);
insert into processoSocorro values (36);
insert into processoSocorro values (37);
insert into processoSocorro values (38);
insert into processoSocorro values (39);
insert into processoSocorro values (40);
insert into processoSocorro values (41);
insert into processoSocorro values (42);
insert into processoSocorro values (43);
insert into processoSocorro values (44);
insert into processoSocorro values (45);
insert into processoSocorro values (46);
insert into processoSocorro values (47);
insert into processoSocorro values (48);
insert into processoSocorro values (49);
insert into processoSocorro values (50);
insert into processoSocorro values (51);
insert into processoSocorro values (52);
insert into processoSocorro values (53);
insert into processoSocorro values (54);
insert into processoSocorro values (55);
insert into processoSocorro values (56);
insert into processoSocorro values (57);
insert into processoSocorro values (58);
insert into processoSocorro values (59);
insert into processoSocorro values (60);
insert into processoSocorro values (61);
insert into processoSocorro values (62);
insert into processoSocorro values (63);
insert into processoSocorro values (64);
insert into processoSocorro values (65);
insert into processoSocorro values (66);
insert into processoSocorro values (67);
insert into processoSocorro values (68);
insert into processoSocorro values (69);
insert into processoSocorro values (70);
insert into processoSocorro values (71);
insert into processoSocorro values (72);
insert into processoSocorro values (73);
insert into processoSocorro values (74);
insert into processoSocorro values (75);
insert into processoSocorro values (76);
insert into processoSocorro values (77);
insert into processoSocorro values (78);
insert into processoSocorro values (79);
insert into processoSocorro values (80);
insert into processoSocorro values (81);
insert into processoSocorro values (82);
insert into processoSocorro values (83);
insert into processoSocorro values (84);
insert into processoSocorro values (85);
insert into processoSocorro values (86);
insert into processoSocorro values (87);
insert into processoSocorro values (88);
insert into processoSocorro values (89);
insert into processoSocorro values (90);
insert into processoSocorro values (91);
insert into processoSocorro values (92);
insert into processoSocorro values (93);
insert into processoSocorro values (94);
insert into processoSocorro values (95);
insert into processoSocorro values (96);
insert into processoSocorro values (97);
insert into processoSocorro values (98);
insert into processoSocorro values (99);

insert into local values ('Albergaria-a-Velha');
insert into local values ('Proenca-a-Nova');
insert into local values ('Valpacos');
insert into local values ('Aljustrel');
insert into local values ('Sao Pedro do Sul');
insert into local values ('Castro Daire');
insert into local values ('Batalha');
insert into local values ('Torres Vedras');
insert into local values ('Sesimbra');
insert into local values ('Tondela');
insert into local values ('Vila Verde');
insert into local values ('Amares');
insert into local values ('Ferreira do Alentejo');
insert into local values ('Penacova');
insert into local values ('Salvaterra de Magos');
insert into local values ('Santarem');
insert into local values ('Alenquer');
insert into local values ('Caldas da Rainha');
insert into local values ('Vila Real');
insert into local values ('Boticas');
insert into local values ('Vila Flor');
insert into local values ('Velas');
insert into local values ('Sardoal');
insert into local values ('Castanheira de Pera');
insert into local values ('Celorico de Basto');
insert into local values ('Belmonte');
insert into local values ('Almada');
insert into local values ('Lourinha');
insert into local values ('Vila do Porto');
insert into local values ('Mira');
insert into local values ('Povoa de Varzim');
insert into local values ('Moura');
insert into local values ('Vila Nova de Famalicao');
insert into local values ('Nisa');
insert into local values ('Gondomar');
insert into local values ('Viana do Castelo');
insert into local values ('Felgueiras');
insert into local values ('Guarda');
insert into local values ('Odivelas');
insert into local values ('Odemira');
insert into local values ('Fafe');
insert into local values ('Ourique');
insert into local values ('Penela');
insert into local values ('Vila Nova de Cerveira');
insert into local values ('Vila Franca do Campo');
insert into local values ('Agueda');
insert into local values ('Marco de Canaveses');
insert into local values ('Arouca');
insert into local values ('Penedono');
insert into local values ('Vila Nova de Paiva');
insert into local values ('Trancoso');
insert into local values ('Sever do Vouga');
insert into local values ('Loures');
insert into local values ('Cantanhede');
insert into local values ('Viana do Alentejo');
insert into local values ('Aljezur');
insert into local values ('Vila Nova de Poiares');
insert into local values ('Evora');
insert into local values ('Alpiarca');
insert into local values ('Marvao');
insert into local values ('Lousada');
insert into local values ('Crato');
insert into local values ('Campo Maior');
insert into local values ('Vinhais');
insert into local values ('Caminha');
insert into local values ('Moita');
insert into local values ('Penafiel');
insert into local values ('Amarante');
insert into local values ('Nelas');
insert into local values ('Alandroal');
insert into local values ('Penalva do Castelo');
insert into local values ('Alijo');
insert into local values ('Cabeceiras de Basto');
insert into local values ('Montemor-o-Velho');
insert into local values ('Cartaxo');
insert into local values ('Aveiro');
insert into local values ('Vila Real de Santo Antonio');
insert into local values ('Espinho');
insert into local values ('Barrancos');
insert into local values ('Coruche');
insert into local values ('Santa Cruz das Flores');
insert into local values ('Moncao');
insert into local values ('Tarouca');
insert into local values ('Mondim de Basto');
insert into local values ('Santa Marta de Penaguiao');
insert into local values ('Pampilhosa da Serra');
insert into local values ('Lagoa');
insert into local values ('Santa Cruz');
insert into local values ('Terras de Bouro');
insert into local values ('Sernancelhe');
insert into local values ('Cuba');
insert into local values ('Alfandega da Fe');
insert into local values ('Ovar');
insert into local values ('Palmela');
insert into local values ('Sobral de Monte Agraco');
insert into local values ('Golega');
insert into local values ('Vieira do Minho');
insert into local values ('Ansiao');
insert into local values ('Beja');
insert into local values ('Arruda dos Vinhos');
insert into local values ('Serpa');
insert into local values ('Vila Nova de Foz Coa');
insert into local values ('Bombarral');
insert into local values ('Maia');
insert into local values ('Alcochete');
insert into local values ('Praia da Vitoria');
insert into local values ('Sabrosa');
insert into local values ('Matosinhos');
insert into local values ('Cascais');
insert into local values ('Mafra');
insert into local values ('Figueira de Castelo Rodrigo');
insert into local values ('Monchique');
insert into local values ('Paredes');
insert into local values ('Coimbra');
insert into local values ('Arcos de Valdevez');
insert into local values ('Ribeira de Pena');
insert into local values ('Serta');
insert into local values ('Calheta');
insert into local values ('Oliveira de Azemeis');
insert into local values ('Miranda do Corvo');
insert into local values ('Vila Velha de Rodao');
insert into local values ('Arganil');
insert into local values ('Sabugal');
insert into local values ('Santa Comba Dao');
insert into local values ('Arraiolos');
insert into local values ('Murtosa');
insert into local values ('Guimaraes');
insert into local values ('Vale de Cambra');
insert into local values ('Montalegre');
insert into local values ('Condeixa-a-Nova');
insert into local values ('Vila do Bispo');
insert into local values ('Ourem');
insert into local values ('Loule');
insert into local values ('Braganca');
insert into local values ('Ponte da Barca');
insert into local values ('Constancia');
insert into local values ('Avis');
insert into local values ('Montemor-o-Novo');
insert into local values ('Grandola');
insert into local values ('Abrantes');
insert into local values ('Fronteira');
insert into local values ('Castelo de Paiva');
insert into local values ('Sao Joao da Pesqueira');
insert into local values ('Almeirim');
insert into local values ('Machico');
insert into local values ('Fornos de Algodres');
insert into local values ('Seia');
insert into local values ('Povoacao');
insert into local values ('Marinha Grande');
insert into local values ('Vila Nova de Gaia');
insert into local values ('Figueira da Foz');
insert into local values ('Alcobaca');
insert into local values ('Oliveira de Frades');
insert into local values ('Alter do Chao');
insert into local values ('Freixo de Espada a Cinta');
insert into local values ('Pedrogao Grande');
insert into local values ('Tavira');
insert into local values ('Vimioso');
insert into local values ('Baiao');
insert into local values ('Corvo');
insert into local values ('Rio Maior');
insert into local values ('Mourao');
insert into local values ('Monforte');
insert into local values ('Fundao');
insert into local values ('Sao Bras de Alportel');
insert into local values ('Chaves');
insert into local values ('Azambuja');
insert into local values ('Santa Cruz da Graciosa');
insert into local values ('Porto de Mos');
insert into local values ('Vizela');
insert into local values ('Ponta do Sol');
insert into local values ('Ilhavo');
insert into local values ('Vidigueira');
insert into local values ('Povoa de Lanhoso');
insert into local values ('Gois');
insert into local values ('Carregal do Sal');
insert into local values ('Angra do Heroismo');
insert into local values ('Sao Vicente');
insert into local values ('Madalena');
insert into local values ('Carrazeda de Ansiaes');
insert into local values ('Oeiras');
insert into local values ('Porto Moniz');
insert into local values ('Vila Franca de Xira');
insert into local values ('Torres Novas');
insert into local values ('Sintra');
insert into local values ('Castelo Branco');
insert into local values ('Valongo');
insert into local values ('Anadia');
insert into local values ('Leiria');
insert into local values ('Sousel');
insert into local values ('Camara de Lobos');
insert into local values ('Santiago do Cacem');
insert into local values ('Cadaval');
insert into local values ('Figueiro dos Vinhos');
insert into local values ('Lousa');
insert into local values ('Satao');
insert into local values ('Almeida');
insert into local values ('Soure');
insert into local values ('Castro Marim');
insert into local values ('Lagos');
insert into local values ('Aguiar da Beira');
insert into local values ('Santo Tirso');
insert into local values ('Mortagua');
insert into local values ('Lisboa');
insert into local values ('Oliveira do Hospital');
insert into local values ('Vila Nova da Barquinha');
insert into local values ('Chamusca');
insert into local values ('Alcacer do Sal');
insert into local values ('Covilha');
insert into local values ('Viseu');
insert into local values ('Vila Pouca de Aguiar');
insert into local values ('Ribeira Grande');
insert into local values ('Mertola');
insert into local values ('Almodovar');
insert into local values ('Barreiro');
insert into local values ('Ponta Delgada');
insert into local values ('Arronches');
insert into local values ('Mora');
insert into local values ('Seixal');
insert into local values ('Pombal');
insert into local values ('Esposende');
insert into local values ('Manteigas');
insert into local values ('Alvito');
insert into local values ('Castro Verde');
insert into local values ('Portel');
insert into local values ('Oleiros');
insert into local values ('Lajes das Flores');
insert into local values ('Silves');
insert into local values ('Cinfaes');
insert into local values ('Vouzela');
insert into local values ('Macao');
insert into local values ('Resende');
insert into local values ('Redondo');
insert into local values ('Alcanena');
insert into local values ('Alcoutim');
insert into local values ('Lajes do Pico');
insert into local values ('Vila de Rei');
insert into local values ('Penamacor');
insert into local values ('Nordeste');
insert into local values ('Mogadouro');
insert into local values ('Oliveira do Bairro');
insert into local values ('Estarreja');
insert into local values ('Mealhada');
insert into local values ('Tabuaco');
insert into local values ('Celorico da Beira');
insert into local values ('Pacos de Ferreira');
insert into local values ('Trofa');
insert into local values ('Nazare');
insert into local values ('Sao Roque do Pico');
insert into local values ('Olhao');
insert into local values ('Murca');
insert into local values ('Mesao Frio');
insert into local values ('Castelo de Vide');
insert into local values ('Torre de Moncorvo');
insert into local values ('Tabua');
insert into local values ('Mirandela');
insert into local values ('Meda');
insert into local values ('Peniche');
insert into local values ('Lamego');
insert into local values ('Santa Maria da Feira');
insert into local values ('Armamar');
insert into local values ('Ponte de Lima');
insert into local values ('Paredes de Coura');
insert into local values ('Gouveia');
insert into local values ('Miranda do Douro');
insert into local values ('Moimenta da Beira');
insert into local values ('Ferreira do Zezere');
insert into local values ('Portimao');
insert into local values ('Obidos');
insert into local values ('Ribeira Brava');
insert into local values ('Idanha-a-Nova');
insert into local values ('Gaviao');
insert into local values ('Vagos');
insert into local values ('Benavente');
insert into local values ('Alvaiazere');
insert into local values ('Melgaco');
insert into local values ('Vila Vicosa');

insert into entidadeMeio values ('Bombeiros de Albergaria-a-Velha');
insert into entidadeMeio values ('Policia Municipal de Albergaria-a-Velha');
insert into entidadeMeio values ('Bombeiros de Proenca-a-Nova');
insert into entidadeMeio values ('Policia Municipal de Proenca-a-Nova');
insert into entidadeMeio values ('Bombeiros de Valpacos');
insert into entidadeMeio values ('Policia Municipal de Valpacos');
insert into entidadeMeio values ('Bombeiros de Aljustrel');
insert into entidadeMeio values ('Policia Municipal de Aljustrel');
insert into entidadeMeio values ('Bombeiros de Sao Pedro do Sul');
insert into entidadeMeio values ('Policia Municipal de Sao Pedro do Sul');
insert into entidadeMeio values ('Bombeiros de Castro Daire');
insert into entidadeMeio values ('Policia Municipal de Castro Daire');
insert into entidadeMeio values ('Bombeiros de Batalha');
insert into entidadeMeio values ('Policia Municipal de Batalha');
insert into entidadeMeio values ('Bombeiros de Torres Vedras');
insert into entidadeMeio values ('Policia Municipal de Torres Vedras');
insert into entidadeMeio values ('Bombeiros de Sesimbra');
insert into entidadeMeio values ('Policia Municipal de Sesimbra');
insert into entidadeMeio values ('Bombeiros de Tondela');
insert into entidadeMeio values ('Policia Municipal de Tondela');
insert into entidadeMeio values ('Bombeiros de Vila Verde');
insert into entidadeMeio values ('Policia Municipal de Vila Verde');
insert into entidadeMeio values ('Bombeiros de Amares');
insert into entidadeMeio values ('Policia Municipal de Amares');
insert into entidadeMeio values ('Bombeiros de Ferreira do Alentejo');
insert into entidadeMeio values ('Policia Municipal de Ferreira do Alentejo');
insert into entidadeMeio values ('Bombeiros de Penacova');
insert into entidadeMeio values ('Policia Municipal de Penacova');
insert into entidadeMeio values ('Bombeiros de Salvaterra de Magos');
insert into entidadeMeio values ('Policia Municipal de Salvaterra de Magos');
insert into entidadeMeio values ('Bombeiros de Santarem');
insert into entidadeMeio values ('Policia Municipal de Santarem');
insert into entidadeMeio values ('Bombeiros de Alenquer');
insert into entidadeMeio values ('Policia Municipal de Alenquer');
insert into entidadeMeio values ('Bombeiros de Caldas da Rainha');
insert into entidadeMeio values ('Policia Municipal de Caldas da Rainha');
insert into entidadeMeio values ('Bombeiros de Vila Real');
insert into entidadeMeio values ('Policia Municipal de Vila Real');
insert into entidadeMeio values ('Bombeiros de Boticas');
insert into entidadeMeio values ('Policia Municipal de Boticas');
insert into entidadeMeio values ('Bombeiros de Vila Flor');
insert into entidadeMeio values ('Policia Municipal de Vila Flor');
insert into entidadeMeio values ('Bombeiros de Velas');
insert into entidadeMeio values ('Policia Municipal de Velas');
insert into entidadeMeio values ('Bombeiros de Sardoal');
insert into entidadeMeio values ('Policia Municipal de Sardoal');
insert into entidadeMeio values ('Bombeiros de Castanheira de Pera');
insert into entidadeMeio values ('Policia Municipal de Castanheira de Pera');
insert into entidadeMeio values ('Bombeiros de Celorico de Basto');
insert into entidadeMeio values ('Policia Municipal de Celorico de Basto');
insert into entidadeMeio values ('Bombeiros de Belmonte');
insert into entidadeMeio values ('Policia Municipal de Belmonte');
insert into entidadeMeio values ('Bombeiros de Almada');
insert into entidadeMeio values ('Policia Municipal de Almada');
insert into entidadeMeio values ('Bombeiros de Lourinha');
insert into entidadeMeio values ('Policia Municipal de Lourinha');
insert into entidadeMeio values ('Bombeiros de Vila do Porto');
insert into entidadeMeio values ('Policia Municipal de Vila do Porto');
insert into entidadeMeio values ('Bombeiros de Mira');
insert into entidadeMeio values ('Policia Municipal de Mira');
insert into entidadeMeio values ('Bombeiros de Povoa de Varzim');
insert into entidadeMeio values ('Policia Municipal de Povoa de Varzim');
insert into entidadeMeio values ('Bombeiros de Moura');
insert into entidadeMeio values ('Policia Municipal de Moura');
insert into entidadeMeio values ('Bombeiros de Vila Nova de Famalicao');
insert into entidadeMeio values ('Policia Municipal de Vila Nova de Famalicao');
insert into entidadeMeio values ('Bombeiros de Nisa');
insert into entidadeMeio values ('Policia Municipal de Nisa');
insert into entidadeMeio values ('Bombeiros de Gondomar');
insert into entidadeMeio values ('Policia Municipal de Gondomar');
insert into entidadeMeio values ('Bombeiros de Viana do Castelo');
insert into entidadeMeio values ('Policia Municipal de Viana do Castelo');
insert into entidadeMeio values ('Bombeiros de Felgueiras');
insert into entidadeMeio values ('Policia Municipal de Felgueiras');
insert into entidadeMeio values ('Bombeiros de Guarda');
insert into entidadeMeio values ('Policia Municipal de Guarda');
insert into entidadeMeio values ('Bombeiros de Odivelas');
insert into entidadeMeio values ('Policia Municipal de Odivelas');
insert into entidadeMeio values ('Bombeiros de Odemira');
insert into entidadeMeio values ('Policia Municipal de Odemira');
insert into entidadeMeio values ('Bombeiros de Fafe');
insert into entidadeMeio values ('Policia Municipal de Fafe');
insert into entidadeMeio values ('Bombeiros de Ourique');
insert into entidadeMeio values ('Policia Municipal de Ourique');
insert into entidadeMeio values ('Bombeiros de Penela');
insert into entidadeMeio values ('Policia Municipal de Penela');
insert into entidadeMeio values ('Bombeiros de Vila Nova de Cerveira');
insert into entidadeMeio values ('Policia Municipal de Vila Nova de Cerveira');
insert into entidadeMeio values ('Bombeiros de Vila Franca do Campo');
insert into entidadeMeio values ('Policia Municipal de Vila Franca do Campo');
insert into entidadeMeio values ('Bombeiros de Agueda');
insert into entidadeMeio values ('Policia Municipal de Agueda');
insert into entidadeMeio values ('Bombeiros de Marco de Canaveses');
insert into entidadeMeio values ('Policia Municipal de Marco de Canaveses');
insert into entidadeMeio values ('Bombeiros de Arouca');
insert into entidadeMeio values ('Policia Municipal de Arouca');
insert into entidadeMeio values ('Bombeiros de Penedono');
insert into entidadeMeio values ('Policia Municipal de Penedono');
insert into entidadeMeio values ('Bombeiros de Vila Nova de Paiva');
insert into entidadeMeio values ('Policia Municipal de Vila Nova de Paiva');
insert into entidadeMeio values ('Bombeiros de Trancoso');
insert into entidadeMeio values ('Policia Municipal de Trancoso');
insert into entidadeMeio values ('Bombeiros de Sever do Vouga');
insert into entidadeMeio values ('Policia Municipal de Sever do Vouga');
insert into entidadeMeio values ('Bombeiros de Loures');
insert into entidadeMeio values ('Policia Municipal de Loures');
insert into entidadeMeio values ('Bombeiros de Cantanhede');
insert into entidadeMeio values ('Policia Municipal de Cantanhede');
insert into entidadeMeio values ('Bombeiros de Viana do Alentejo');
insert into entidadeMeio values ('Policia Municipal de Viana do Alentejo');
insert into entidadeMeio values ('Bombeiros de Aljezur');
insert into entidadeMeio values ('Policia Municipal de Aljezur');
insert into entidadeMeio values ('Bombeiros de Vila Nova de Poiares');
insert into entidadeMeio values ('Policia Municipal de Vila Nova de Poiares');
insert into entidadeMeio values ('Bombeiros de Evora');
insert into entidadeMeio values ('Policia Municipal de Evora');
insert into entidadeMeio values ('Bombeiros de Alpiarca');
insert into entidadeMeio values ('Policia Municipal de Alpiarca');
insert into entidadeMeio values ('Bombeiros de Marvao');
insert into entidadeMeio values ('Policia Municipal de Marvao');
insert into entidadeMeio values ('Bombeiros de Lousada');
insert into entidadeMeio values ('Policia Municipal de Lousada');
insert into entidadeMeio values ('Bombeiros de Crato');
insert into entidadeMeio values ('Policia Municipal de Crato');
insert into entidadeMeio values ('Bombeiros de Campo Maior');
insert into entidadeMeio values ('Policia Municipal de Campo Maior');
insert into entidadeMeio values ('Bombeiros de Vinhais');
insert into entidadeMeio values ('Policia Municipal de Vinhais');
insert into entidadeMeio values ('Bombeiros de Caminha');
insert into entidadeMeio values ('Policia Municipal de Caminha');
insert into entidadeMeio values ('Bombeiros de Moita');
insert into entidadeMeio values ('Policia Municipal de Moita');
insert into entidadeMeio values ('Bombeiros de Penafiel');
insert into entidadeMeio values ('Policia Municipal de Penafiel');
insert into entidadeMeio values ('Bombeiros de Amarante');
insert into entidadeMeio values ('Policia Municipal de Amarante');
insert into entidadeMeio values ('Bombeiros de Nelas');
insert into entidadeMeio values ('Policia Municipal de Nelas');
insert into entidadeMeio values ('Bombeiros de Alandroal');
insert into entidadeMeio values ('Policia Municipal de Alandroal');
insert into entidadeMeio values ('Bombeiros de Penalva do Castelo');
insert into entidadeMeio values ('Policia Municipal de Penalva do Castelo');
insert into entidadeMeio values ('Bombeiros de Alijo');
insert into entidadeMeio values ('Policia Municipal de Alijo');
insert into entidadeMeio values ('Bombeiros de Cabeceiras de Basto');
insert into entidadeMeio values ('Policia Municipal de Cabeceiras de Basto');
insert into entidadeMeio values ('Bombeiros de Montemor-o-Velho');
insert into entidadeMeio values ('Policia Municipal de Montemor-o-Velho');
insert into entidadeMeio values ('Bombeiros de Cartaxo');
insert into entidadeMeio values ('Policia Municipal de Cartaxo');
insert into entidadeMeio values ('Bombeiros de Aveiro');
insert into entidadeMeio values ('Policia Municipal de Aveiro');
insert into entidadeMeio values ('Bombeiros de Vila Real de Santo Antonio');
insert into entidadeMeio values ('Policia Municipal de Vila Real de Santo Antonio');
insert into entidadeMeio values ('Bombeiros de Espinho');
insert into entidadeMeio values ('Policia Municipal de Espinho');
insert into entidadeMeio values ('Bombeiros de Barrancos');
insert into entidadeMeio values ('Policia Municipal de Barrancos');
insert into entidadeMeio values ('Bombeiros de Coruche');
insert into entidadeMeio values ('Policia Municipal de Coruche');
insert into entidadeMeio values ('Bombeiros de Santa Cruz das Flores');
insert into entidadeMeio values ('Policia Municipal de Santa Cruz das Flores');
insert into entidadeMeio values ('Bombeiros de Moncao');
insert into entidadeMeio values ('Policia Municipal de Moncao');
insert into entidadeMeio values ('Bombeiros de Tarouca');
insert into entidadeMeio values ('Policia Municipal de Tarouca');
insert into entidadeMeio values ('Bombeiros de Mondim de Basto');
insert into entidadeMeio values ('Policia Municipal de Mondim de Basto');
insert into entidadeMeio values ('Bombeiros de Santa Marta de Penaguiao');
insert into entidadeMeio values ('Policia Municipal de Santa Marta de Penaguiao');
insert into entidadeMeio values ('Bombeiros de Pampilhosa da Serra');
insert into entidadeMeio values ('Policia Municipal de Pampilhosa da Serra');
insert into entidadeMeio values ('Bombeiros de Lagoa');
insert into entidadeMeio values ('Policia Municipal de Lagoa');
insert into entidadeMeio values ('Bombeiros de Santa Cruz');
insert into entidadeMeio values ('Policia Municipal de Santa Cruz');
insert into entidadeMeio values ('Bombeiros de Terras de Bouro');
insert into entidadeMeio values ('Policia Municipal de Terras de Bouro');
insert into entidadeMeio values ('Bombeiros de Sernancelhe');
insert into entidadeMeio values ('Policia Municipal de Sernancelhe');
insert into entidadeMeio values ('Bombeiros de Cuba');
insert into entidadeMeio values ('Policia Municipal de Cuba');
insert into entidadeMeio values ('Bombeiros de Alfandega da Fe');
insert into entidadeMeio values ('Policia Municipal de Alfandega da Fe');
insert into entidadeMeio values ('Bombeiros de Ovar');
insert into entidadeMeio values ('Policia Municipal de Ovar');
insert into entidadeMeio values ('Bombeiros de Palmela');
insert into entidadeMeio values ('Policia Municipal de Palmela');
insert into entidadeMeio values ('Bombeiros de Sobral de Monte Agraco');
insert into entidadeMeio values ('Policia Municipal de Sobral de Monte Agraco');
insert into entidadeMeio values ('Bombeiros de Golega');
insert into entidadeMeio values ('Policia Municipal de Golega');
insert into entidadeMeio values ('Bombeiros de Vieira do Minho');
insert into entidadeMeio values ('Policia Municipal de Vieira do Minho');
insert into entidadeMeio values ('Bombeiros de Ansiao');
insert into entidadeMeio values ('Policia Municipal de Ansiao');
insert into entidadeMeio values ('Bombeiros de Beja');
insert into entidadeMeio values ('Policia Municipal de Beja');
insert into entidadeMeio values ('Bombeiros de Arruda dos Vinhos');
insert into entidadeMeio values ('Policia Municipal de Arruda dos Vinhos');
insert into entidadeMeio values ('Bombeiros de Serpa');
insert into entidadeMeio values ('Policia Municipal de Serpa');
insert into entidadeMeio values ('Bombeiros de Vila Nova de Foz Coa');
insert into entidadeMeio values ('Policia Municipal de Vila Nova de Foz Coa');
insert into entidadeMeio values ('Bombeiros de Bombarral');
insert into entidadeMeio values ('Policia Municipal de Bombarral');
insert into entidadeMeio values ('Bombeiros de Maia');
insert into entidadeMeio values ('Policia Municipal de Maia');
insert into entidadeMeio values ('Bombeiros de Alcochete');
insert into entidadeMeio values ('Policia Municipal de Alcochete');
insert into entidadeMeio values ('Bombeiros de Praia da Vitoria');
insert into entidadeMeio values ('Policia Municipal de Praia da Vitoria');
insert into entidadeMeio values ('Bombeiros de Sabrosa');
insert into entidadeMeio values ('Policia Municipal de Sabrosa');
insert into entidadeMeio values ('Bombeiros de Matosinhos');
insert into entidadeMeio values ('Policia Municipal de Matosinhos');
insert into entidadeMeio values ('Bombeiros de Cascais');
insert into entidadeMeio values ('Policia Municipal de Cascais');
insert into entidadeMeio values ('Bombeiros de Mafra');
insert into entidadeMeio values ('Policia Municipal de Mafra');
insert into entidadeMeio values ('Bombeiros de Figueira de Castelo Rodrigo');
insert into entidadeMeio values ('Policia Municipal de Figueira de Castelo Rodrigo');
insert into entidadeMeio values ('Bombeiros de Monchique');
insert into entidadeMeio values ('Policia Municipal de Monchique');
insert into entidadeMeio values ('Bombeiros de Paredes');
insert into entidadeMeio values ('Policia Municipal de Paredes');
insert into entidadeMeio values ('Bombeiros de Coimbra');
insert into entidadeMeio values ('Policia Municipal de Coimbra');
insert into entidadeMeio values ('Bombeiros de Arcos de Valdevez');
insert into entidadeMeio values ('Policia Municipal de Arcos de Valdevez');
insert into entidadeMeio values ('Bombeiros de Ribeira de Pena');
insert into entidadeMeio values ('Policia Municipal de Ribeira de Pena');
insert into entidadeMeio values ('Bombeiros de Serta');
insert into entidadeMeio values ('Policia Municipal de Serta');
insert into entidadeMeio values ('Bombeiros de Calheta');
insert into entidadeMeio values ('Policia Municipal de Calheta');
insert into entidadeMeio values ('Bombeiros de Oliveira de Azemeis');
insert into entidadeMeio values ('Policia Municipal de Oliveira de Azemeis');
insert into entidadeMeio values ('Bombeiros de Miranda do Corvo');
insert into entidadeMeio values ('Policia Municipal de Miranda do Corvo');
insert into entidadeMeio values ('Bombeiros de Vila Velha de Rodao');
insert into entidadeMeio values ('Policia Municipal de Vila Velha de Rodao');
insert into entidadeMeio values ('Bombeiros de Arganil');
insert into entidadeMeio values ('Policia Municipal de Arganil');
insert into entidadeMeio values ('Bombeiros de Sabugal');
insert into entidadeMeio values ('Policia Municipal de Sabugal');
insert into entidadeMeio values ('Bombeiros de Santa Comba Dao');
insert into entidadeMeio values ('Policia Municipal de Santa Comba Dao');
insert into entidadeMeio values ('Bombeiros de Arraiolos');
insert into entidadeMeio values ('Policia Municipal de Arraiolos');
insert into entidadeMeio values ('Bombeiros de Murtosa');
insert into entidadeMeio values ('Policia Municipal de Murtosa');
insert into entidadeMeio values ('Bombeiros de Guimaraes');
insert into entidadeMeio values ('Policia Municipal de Guimaraes');
insert into entidadeMeio values ('Bombeiros de Vale de Cambra');
insert into entidadeMeio values ('Policia Municipal de Vale de Cambra');
insert into entidadeMeio values ('Bombeiros de Montalegre');
insert into entidadeMeio values ('Policia Municipal de Montalegre');
insert into entidadeMeio values ('Bombeiros de Condeixa-a-Nova');
insert into entidadeMeio values ('Policia Municipal de Condeixa-a-Nova');
insert into entidadeMeio values ('Bombeiros de Vila do Bispo');
insert into entidadeMeio values ('Policia Municipal de Vila do Bispo');
insert into entidadeMeio values ('Bombeiros de Ourem');
insert into entidadeMeio values ('Policia Municipal de Ourem');
insert into entidadeMeio values ('Bombeiros de Loule');
insert into entidadeMeio values ('Policia Municipal de Loule');
insert into entidadeMeio values ('Bombeiros de Braganca');
insert into entidadeMeio values ('Policia Municipal de Braganca');
insert into entidadeMeio values ('Bombeiros de Ponte da Barca');
insert into entidadeMeio values ('Policia Municipal de Ponte da Barca');
insert into entidadeMeio values ('Bombeiros de Constancia');
insert into entidadeMeio values ('Policia Municipal de Constancia');
insert into entidadeMeio values ('Bombeiros de Avis');
insert into entidadeMeio values ('Policia Municipal de Avis');
insert into entidadeMeio values ('Bombeiros de Montemor-o-Novo');
insert into entidadeMeio values ('Policia Municipal de Montemor-o-Novo');
insert into entidadeMeio values ('Bombeiros de Grandola');
insert into entidadeMeio values ('Policia Municipal de Grandola');
insert into entidadeMeio values ('Bombeiros de Abrantes');
insert into entidadeMeio values ('Policia Municipal de Abrantes');
insert into entidadeMeio values ('Bombeiros de Fronteira');
insert into entidadeMeio values ('Policia Municipal de Fronteira');
insert into entidadeMeio values ('Bombeiros de Castelo de Paiva');
insert into entidadeMeio values ('Policia Municipal de Castelo de Paiva');
insert into entidadeMeio values ('Bombeiros de Sao Joao da Pesqueira');
insert into entidadeMeio values ('Policia Municipal de Sao Joao da Pesqueira');
insert into entidadeMeio values ('Bombeiros de Almeirim');
insert into entidadeMeio values ('Policia Municipal de Almeirim');
insert into entidadeMeio values ('Bombeiros de Machico');
insert into entidadeMeio values ('Policia Municipal de Machico');
insert into entidadeMeio values ('Bombeiros de Fornos de Algodres');
insert into entidadeMeio values ('Policia Municipal de Fornos de Algodres');
insert into entidadeMeio values ('Bombeiros de Seia');
insert into entidadeMeio values ('Policia Municipal de Seia');
insert into entidadeMeio values ('Bombeiros de Povoacao');
insert into entidadeMeio values ('Policia Municipal de Povoacao');
insert into entidadeMeio values ('Bombeiros de Marinha Grande');
insert into entidadeMeio values ('Policia Municipal de Marinha Grande');
insert into entidadeMeio values ('Bombeiros de Vila Nova de Gaia');
insert into entidadeMeio values ('Policia Municipal de Vila Nova de Gaia');
insert into entidadeMeio values ('Bombeiros de Figueira da Foz');
insert into entidadeMeio values ('Policia Municipal de Figueira da Foz');
insert into entidadeMeio values ('Bombeiros de Alcobaca');
insert into entidadeMeio values ('Policia Municipal de Alcobaca');
insert into entidadeMeio values ('Bombeiros de Oliveira de Frades');
insert into entidadeMeio values ('Policia Municipal de Oliveira de Frades');
insert into entidadeMeio values ('Bombeiros de Alter do Chao');
insert into entidadeMeio values ('Policia Municipal de Alter do Chao');
insert into entidadeMeio values ('Bombeiros de Freixo de Espada a Cinta');
insert into entidadeMeio values ('Policia Municipal de Freixo de Espada a Cinta');
insert into entidadeMeio values ('Bombeiros de Pedrogao Grande');
insert into entidadeMeio values ('Policia Municipal de Pedrogao Grande');
insert into entidadeMeio values ('Bombeiros de Tavira');
insert into entidadeMeio values ('Policia Municipal de Tavira');
insert into entidadeMeio values ('Bombeiros de Vimioso');
insert into entidadeMeio values ('Policia Municipal de Vimioso');
insert into entidadeMeio values ('Bombeiros de Baiao');
insert into entidadeMeio values ('Policia Municipal de Baiao');
insert into entidadeMeio values ('Bombeiros de Corvo');
insert into entidadeMeio values ('Policia Municipal de Corvo');
insert into entidadeMeio values ('Bombeiros de Rio Maior');
insert into entidadeMeio values ('Policia Municipal de Rio Maior');
insert into entidadeMeio values ('Bombeiros de Mourao');
insert into entidadeMeio values ('Policia Municipal de Mourao');
insert into entidadeMeio values ('Bombeiros de Monforte');
insert into entidadeMeio values ('Policia Municipal de Monforte');
insert into entidadeMeio values ('Bombeiros de Fundao');
insert into entidadeMeio values ('Policia Municipal de Fundao');
insert into entidadeMeio values ('Bombeiros de Sao Bras de Alportel');
insert into entidadeMeio values ('Policia Municipal de Sao Bras de Alportel');
insert into entidadeMeio values ('Bombeiros de Chaves');
insert into entidadeMeio values ('Policia Municipal de Chaves');
insert into entidadeMeio values ('Bombeiros de Azambuja');
insert into entidadeMeio values ('Policia Municipal de Azambuja');
insert into entidadeMeio values ('Bombeiros de Santa Cruz da Graciosa');
insert into entidadeMeio values ('Policia Municipal de Santa Cruz da Graciosa');
insert into entidadeMeio values ('Bombeiros de Porto de Mos');
insert into entidadeMeio values ('Policia Municipal de Porto de Mos');
insert into entidadeMeio values ('Bombeiros de Vizela');
insert into entidadeMeio values ('Policia Municipal de Vizela');
insert into entidadeMeio values ('Bombeiros de Ponta do Sol');
insert into entidadeMeio values ('Policia Municipal de Ponta do Sol');
insert into entidadeMeio values ('Bombeiros de Ilhavo');
insert into entidadeMeio values ('Policia Municipal de Ilhavo');
insert into entidadeMeio values ('Bombeiros de Vidigueira');
insert into entidadeMeio values ('Policia Municipal de Vidigueira');
insert into entidadeMeio values ('Bombeiros de Povoa de Lanhoso');
insert into entidadeMeio values ('Policia Municipal de Povoa de Lanhoso');
insert into entidadeMeio values ('Bombeiros de Gois');
insert into entidadeMeio values ('Policia Municipal de Gois');
insert into entidadeMeio values ('Bombeiros de Carregal do Sal');
insert into entidadeMeio values ('Policia Municipal de Carregal do Sal');
insert into entidadeMeio values ('Bombeiros de Angra do Heroismo');
insert into entidadeMeio values ('Policia Municipal de Angra do Heroismo');
insert into entidadeMeio values ('Bombeiros de Sao Vicente');
insert into entidadeMeio values ('Policia Municipal de Sao Vicente');
insert into entidadeMeio values ('Bombeiros de Madalena');
insert into entidadeMeio values ('Policia Municipal de Madalena');
insert into entidadeMeio values ('Bombeiros de Carrazeda de Ansiaes');
insert into entidadeMeio values ('Policia Municipal de Carrazeda de Ansiaes');
insert into entidadeMeio values ('Bombeiros de Oeiras');
insert into entidadeMeio values ('Policia Municipal de Oeiras');
insert into entidadeMeio values ('Bombeiros de Porto Moniz');
insert into entidadeMeio values ('Policia Municipal de Porto Moniz');
insert into entidadeMeio values ('Bombeiros de Vila Franca de Xira');
insert into entidadeMeio values ('Policia Municipal de Vila Franca de Xira');
insert into entidadeMeio values ('Bombeiros de Torres Novas');
insert into entidadeMeio values ('Policia Municipal de Torres Novas');
insert into entidadeMeio values ('Bombeiros de Sintra');
insert into entidadeMeio values ('Policia Municipal de Sintra');
insert into entidadeMeio values ('Bombeiros de Castelo Branco');
insert into entidadeMeio values ('Policia Municipal de Castelo Branco');
insert into entidadeMeio values ('Bombeiros de Valongo');
insert into entidadeMeio values ('Policia Municipal de Valongo');
insert into entidadeMeio values ('Bombeiros de Anadia');
insert into entidadeMeio values ('Policia Municipal de Anadia');
insert into entidadeMeio values ('Bombeiros de Leiria');
insert into entidadeMeio values ('Policia Municipal de Leiria');
insert into entidadeMeio values ('Bombeiros de Sousel');
insert into entidadeMeio values ('Policia Municipal de Sousel');
insert into entidadeMeio values ('Bombeiros de Camara de Lobos');
insert into entidadeMeio values ('Policia Municipal de Camara de Lobos');
insert into entidadeMeio values ('Bombeiros de Santiago do Cacem');
insert into entidadeMeio values ('Policia Municipal de Santiago do Cacem');
insert into entidadeMeio values ('Bombeiros de Cadaval');
insert into entidadeMeio values ('Policia Municipal de Cadaval');
insert into entidadeMeio values ('Bombeiros de Figueiro dos Vinhos');
insert into entidadeMeio values ('Policia Municipal de Figueiro dos Vinhos');
insert into entidadeMeio values ('Bombeiros de Lousa');
insert into entidadeMeio values ('Policia Municipal de Lousa');
insert into entidadeMeio values ('Bombeiros de Satao');
insert into entidadeMeio values ('Policia Municipal de Satao');
insert into entidadeMeio values ('Bombeiros de Almeida');
insert into entidadeMeio values ('Policia Municipal de Almeida');
insert into entidadeMeio values ('Bombeiros de Soure');
insert into entidadeMeio values ('Policia Municipal de Soure');
insert into entidadeMeio values ('Bombeiros de Castro Marim');
insert into entidadeMeio values ('Policia Municipal de Castro Marim');
insert into entidadeMeio values ('Bombeiros de Lagos');
insert into entidadeMeio values ('Policia Municipal de Lagos');
insert into entidadeMeio values ('Bombeiros de Aguiar da Beira');
insert into entidadeMeio values ('Policia Municipal de Aguiar da Beira');
insert into entidadeMeio values ('Bombeiros de Santo Tirso');
insert into entidadeMeio values ('Policia Municipal de Santo Tirso');
insert into entidadeMeio values ('Bombeiros de Mortagua');
insert into entidadeMeio values ('Policia Municipal de Mortagua');
insert into entidadeMeio values ('Bombeiros de Lisboa');
insert into entidadeMeio values ('Policia Municipal de Lisboa');
insert into entidadeMeio values ('Bombeiros de Oliveira do Hospital');
insert into entidadeMeio values ('Policia Municipal de Oliveira do Hospital');
insert into entidadeMeio values ('Bombeiros de Vila Nova da Barquinha');
insert into entidadeMeio values ('Policia Municipal de Vila Nova da Barquinha');
insert into entidadeMeio values ('Bombeiros de Chamusca');
insert into entidadeMeio values ('Policia Municipal de Chamusca');
insert into entidadeMeio values ('Bombeiros de Alcacer do Sal');
insert into entidadeMeio values ('Policia Municipal de Alcacer do Sal');
insert into entidadeMeio values ('Bombeiros de Covilha');
insert into entidadeMeio values ('Policia Municipal de Covilha');
insert into entidadeMeio values ('Bombeiros de Viseu');
insert into entidadeMeio values ('Policia Municipal de Viseu');
insert into entidadeMeio values ('Bombeiros de Vila Pouca de Aguiar');
insert into entidadeMeio values ('Policia Municipal de Vila Pouca de Aguiar');
insert into entidadeMeio values ('Bombeiros de Ribeira Grande');
insert into entidadeMeio values ('Policia Municipal de Ribeira Grande');
insert into entidadeMeio values ('Bombeiros de Mertola');
insert into entidadeMeio values ('Policia Municipal de Mertola');
insert into entidadeMeio values ('Bombeiros de Almodovar');
insert into entidadeMeio values ('Policia Municipal de Almodovar');
insert into entidadeMeio values ('Bombeiros de Barreiro');
insert into entidadeMeio values ('Policia Municipal de Barreiro');
insert into entidadeMeio values ('Bombeiros de Ponta Delgada');
insert into entidadeMeio values ('Policia Municipal de Ponta Delgada');
insert into entidadeMeio values ('Bombeiros de Arronches');
insert into entidadeMeio values ('Policia Municipal de Arronches');
insert into entidadeMeio values ('Bombeiros de Mora');
insert into entidadeMeio values ('Policia Municipal de Mora');
insert into entidadeMeio values ('Bombeiros de Seixal');
insert into entidadeMeio values ('Policia Municipal de Seixal');
insert into entidadeMeio values ('Bombeiros de Pombal');
insert into entidadeMeio values ('Policia Municipal de Pombal');
insert into entidadeMeio values ('Bombeiros de Esposende');
insert into entidadeMeio values ('Policia Municipal de Esposende');
insert into entidadeMeio values ('Bombeiros de Manteigas');
insert into entidadeMeio values ('Policia Municipal de Manteigas');
insert into entidadeMeio values ('Bombeiros de Alvito');
insert into entidadeMeio values ('Policia Municipal de Alvito');
insert into entidadeMeio values ('Bombeiros de Castro Verde');
insert into entidadeMeio values ('Policia Municipal de Castro Verde');
insert into entidadeMeio values ('Bombeiros de Portel');
insert into entidadeMeio values ('Policia Municipal de Portel');
insert into entidadeMeio values ('Bombeiros de Oleiros');
insert into entidadeMeio values ('Policia Municipal de Oleiros');
insert into entidadeMeio values ('Bombeiros de Lajes das Flores');
insert into entidadeMeio values ('Policia Municipal de Lajes das Flores');
insert into entidadeMeio values ('Bombeiros de Silves');
insert into entidadeMeio values ('Policia Municipal de Silves');
insert into entidadeMeio values ('Bombeiros de Cinfaes');
insert into entidadeMeio values ('Policia Municipal de Cinfaes');
insert into entidadeMeio values ('Bombeiros de Vouzela');
insert into entidadeMeio values ('Policia Municipal de Vouzela');
insert into entidadeMeio values ('Bombeiros de Macao');
insert into entidadeMeio values ('Policia Municipal de Macao');
insert into entidadeMeio values ('Bombeiros de Resende');
insert into entidadeMeio values ('Policia Municipal de Resende');
insert into entidadeMeio values ('Bombeiros de Redondo');
insert into entidadeMeio values ('Policia Municipal de Redondo');
insert into entidadeMeio values ('Bombeiros de Alcanena');
insert into entidadeMeio values ('Policia Municipal de Alcanena');
insert into entidadeMeio values ('Bombeiros de Alcoutim');
insert into entidadeMeio values ('Policia Municipal de Alcoutim');
insert into entidadeMeio values ('Bombeiros de Lajes do Pico');
insert into entidadeMeio values ('Policia Municipal de Lajes do Pico');
insert into entidadeMeio values ('Bombeiros de Vila de Rei');
insert into entidadeMeio values ('Policia Municipal de Vila de Rei');
insert into entidadeMeio values ('Bombeiros de Penamacor');
insert into entidadeMeio values ('Policia Municipal de Penamacor');
insert into entidadeMeio values ('Bombeiros de Nordeste');
insert into entidadeMeio values ('Policia Municipal de Nordeste');
insert into entidadeMeio values ('Bombeiros de Mogadouro');
insert into entidadeMeio values ('Policia Municipal de Mogadouro');
insert into entidadeMeio values ('Bombeiros de Oliveira do Bairro');
insert into entidadeMeio values ('Policia Municipal de Oliveira do Bairro');
insert into entidadeMeio values ('Bombeiros de Estarreja');
insert into entidadeMeio values ('Policia Municipal de Estarreja');
insert into entidadeMeio values ('Bombeiros de Mealhada');
insert into entidadeMeio values ('Policia Municipal de Mealhada');
insert into entidadeMeio values ('Bombeiros de Tabuaco');
insert into entidadeMeio values ('Policia Municipal de Tabuaco');
insert into entidadeMeio values ('Bombeiros de Celorico da Beira');
insert into entidadeMeio values ('Policia Municipal de Celorico da Beira');
insert into entidadeMeio values ('Bombeiros de Pacos de Ferreira');
insert into entidadeMeio values ('Policia Municipal de Pacos de Ferreira');
insert into entidadeMeio values ('Bombeiros de Trofa');
insert into entidadeMeio values ('Policia Municipal de Trofa');
insert into entidadeMeio values ('Bombeiros de Nazare');
insert into entidadeMeio values ('Policia Municipal de Nazare');
insert into entidadeMeio values ('Bombeiros de Sao Roque do Pico');
insert into entidadeMeio values ('Policia Municipal de Sao Roque do Pico');
insert into entidadeMeio values ('Bombeiros de Olhao');
insert into entidadeMeio values ('Policia Municipal de Olhao');
insert into entidadeMeio values ('Bombeiros de Murca');
insert into entidadeMeio values ('Policia Municipal de Murca');
insert into entidadeMeio values ('Bombeiros de Mesao Frio');
insert into entidadeMeio values ('Policia Municipal de Mesao Frio');
insert into entidadeMeio values ('Bombeiros de Castelo de Vide');
insert into entidadeMeio values ('Policia Municipal de Castelo de Vide');
insert into entidadeMeio values ('Bombeiros de Torre de Moncorvo');
insert into entidadeMeio values ('Policia Municipal de Torre de Moncorvo');
insert into entidadeMeio values ('Bombeiros de Tabua');
insert into entidadeMeio values ('Policia Municipal de Tabua');
insert into entidadeMeio values ('Bombeiros de Mirandela');
insert into entidadeMeio values ('Policia Municipal de Mirandela');
insert into entidadeMeio values ('Bombeiros de Meda');
insert into entidadeMeio values ('Policia Municipal de Meda');
insert into entidadeMeio values ('Bombeiros de Peniche');
insert into entidadeMeio values ('Policia Municipal de Peniche');
insert into entidadeMeio values ('Bombeiros de Lamego');
insert into entidadeMeio values ('Policia Municipal de Lamego');
insert into entidadeMeio values ('Bombeiros de Santa Maria da Feira');
insert into entidadeMeio values ('Policia Municipal de Santa Maria da Feira');
insert into entidadeMeio values ('Bombeiros de Armamar');
insert into entidadeMeio values ('Policia Municipal de Armamar');
insert into entidadeMeio values ('Bombeiros de Ponte de Lima');
insert into entidadeMeio values ('Policia Municipal de Ponte de Lima');
insert into entidadeMeio values ('Bombeiros de Paredes de Coura');
insert into entidadeMeio values ('Policia Municipal de Paredes de Coura');
insert into entidadeMeio values ('Bombeiros de Gouveia');
insert into entidadeMeio values ('Policia Municipal de Gouveia');
insert into entidadeMeio values ('Bombeiros de Miranda do Douro');
insert into entidadeMeio values ('Policia Municipal de Miranda do Douro');
insert into entidadeMeio values ('Bombeiros de Moimenta da Beira');
insert into entidadeMeio values ('Policia Municipal de Moimenta da Beira');
insert into entidadeMeio values ('Bombeiros de Ferreira do Zezere');
insert into entidadeMeio values ('Policia Municipal de Ferreira do Zezere');
insert into entidadeMeio values ('Bombeiros de Portimao');
insert into entidadeMeio values ('Policia Municipal de Portimao');
insert into entidadeMeio values ('Bombeiros de Obidos');
insert into entidadeMeio values ('Policia Municipal de Obidos');
insert into entidadeMeio values ('Bombeiros de Ribeira Brava');
insert into entidadeMeio values ('Policia Municipal de Ribeira Brava');
insert into entidadeMeio values ('Bombeiros de Idanha-a-Nova');
insert into entidadeMeio values ('Policia Municipal de Idanha-a-Nova');
insert into entidadeMeio values ('Bombeiros de Gaviao');
insert into entidadeMeio values ('Policia Municipal de Gaviao');
insert into entidadeMeio values ('Bombeiros de Vagos');
insert into entidadeMeio values ('Policia Municipal de Vagos');
insert into entidadeMeio values ('Bombeiros de Benavente');
insert into entidadeMeio values ('Policia Municipal de Benavente');
insert into entidadeMeio values ('Bombeiros de Alvaiazere');
insert into entidadeMeio values ('Policia Municipal de Alvaiazere');
insert into entidadeMeio values ('Bombeiros de Melgaco');
insert into entidadeMeio values ('Policia Municipal de Melgaco');
insert into entidadeMeio values ('Bombeiros de Vila Vicosa');
insert into entidadeMeio values ('Policia Municipal de Vila Vicosa');
insert into entidadeMeio values ('Exercito');
insert into entidadeMeio values ('Força Aerea');
insert into entidadeMeio values ('PSP');
insert into entidadeMeio values ('GNR');

insert into meio values (22, 'Policia Municipal de Aveiro');
insert into meio values (68, 'Bombeiros de Vila Real');
insert into meio values (85, 'Bombeiros de Arraiolos');
insert into meio values (15, 'Bombeiros de Arruda dos Vinhos');
insert into meio values (98, 'Policia Municipal de Azambuja');
insert into meio values (18, 'Bombeiros de Alter do Chao');
insert into meio values (95, 'Bombeiros de Valpacos');
insert into meio values (72, 'Bombeiros de Vila Pouca de Aguiar');
insert into meio values (19, 'Policia Municipal de Celorico da Beira');
insert into meio values (96, 'Policia Municipal de Esposende');
insert into meio values (53, 'Policia Municipal de Mesao Frio');
insert into meio values (42, 'Policia Municipal de Maia');
insert into meio values (60, 'Bombeiros de Agueda');
insert into meio values (92, 'Bombeiros de Porto Moniz');
insert into meio values (34, 'Bombeiros de Vila Velha de Rodao');
insert into meio values (9, 'Bombeiros de Monchique');
insert into meio values (14, 'Policia Municipal de Moita');
insert into meio values (18, 'Bombeiros de Aljustrel');
insert into meio values (23, 'Policia Municipal de Alcoutim');
insert into meio values (6, 'Policia Municipal de Ourem');
insert into meio values (52, 'Bombeiros de Alcoutim');
insert into meio values (10, 'Bombeiros de Portel');
insert into meio values (84, 'Policia Municipal de Penacova');
insert into meio values (6, 'Policia Municipal de Sesimbra');
insert into meio values (70, 'Bombeiros de Mira');
insert into meio values (58, 'Bombeiros de Rio Maior');
insert into meio values (9, 'Policia Municipal de Moita');
insert into meio values (18, 'Policia Municipal de Alpiarca');
insert into meio values (1, 'Policia Municipal de Avis');
insert into meio values (48, 'Bombeiros de Anadia');
insert into meio values (47, 'Policia Municipal de Espinho');
insert into meio values (86, 'Bombeiros de Angra do Heroismo');
insert into meio values (15, 'Bombeiros de Satao');
insert into meio values (96, 'Bombeiros de Alandroal');
insert into meio values (93, 'Policia Municipal de Odivelas');
insert into meio values (12, 'Policia Municipal de Praia da Vitoria');
insert into meio values (49, 'Policia Municipal de Montalegre');
insert into meio values (18, 'Bombeiros de Angra do Heroismo');
insert into meio values (11, 'Policia Municipal de Guarda');
insert into meio values (58, 'Bombeiros de Santa Marta de Penaguiao');
insert into meio values (17, 'Bombeiros de Valpacos');
insert into meio values (30, 'Bombeiros de Moimenta da Beira');
insert into meio values (63, 'Policia Municipal de Paredes de Coura');
insert into meio values (99, 'Bombeiros de Pacos de Ferreira');
insert into meio values (41, 'Bombeiros de Espinho');
insert into meio values (22, 'Bombeiros de Vila Franca do Campo');
insert into meio values (47, 'Bombeiros de Alpiarca');
insert into meio values (87, 'Policia Municipal de Benavente');
insert into meio values (5, 'Policia Municipal de Soure');
insert into meio values (47, 'Bombeiros de Cascais');
insert into meio values (44, 'Policia Municipal de Portimao');
insert into meio values (32, 'Bombeiros de Penela');
insert into meio values (45, 'Bombeiros de Felgueiras');
insert into meio values (68, 'Bombeiros de Ferreira do Zezere');
insert into meio values (99, 'Bombeiros de Alandroal');
insert into meio values (14, 'Policia Municipal de Evora');
insert into meio values (63, 'Policia Municipal de Espinho');
insert into meio values (96, 'Policia Municipal de Palmela');
insert into meio values (95, 'Bombeiros de Gouveia');
insert into meio values (85, 'Policia Municipal de Aguiar da Beira');
insert into meio values (99, 'Bombeiros de Sernancelhe');
insert into meio values (89, 'Policia Municipal de Moura');
insert into meio values (50, 'Bombeiros de Penamacor');
insert into meio values (81, 'Policia Municipal de Povoa de Lanhoso');
insert into meio values (97, 'Policia Municipal de Salvaterra de Magos');
insert into meio values (25, 'Policia Municipal de Campo Maior');
insert into meio values (31, 'Bombeiros de Ferreira do Alentejo');
insert into meio values (1, 'Bombeiros de Montemor-o-Velho');
insert into meio values (54, 'Policia Municipal de Chaves');
insert into meio values (34, 'Bombeiros de Ansiao');
insert into meio values (37, 'Policia Municipal de Lagos');
insert into meio values (93, 'Policia Municipal de Olhao');
insert into meio values (100, 'Bombeiros de Esposende');
insert into meio values (2, 'Bombeiros de Olhao');
insert into meio values (97, 'Bombeiros de Trofa');
insert into meio values (47, 'Policia Municipal de Sousel');
insert into meio values (3, 'Bombeiros de Lousa');
insert into meio values (48, 'Policia Municipal de Anadia');
insert into meio values (64, 'Bombeiros de Povoa de Varzim');
insert into meio values (90, 'Policia Municipal de Manteigas');
insert into meio values (81, 'Policia Municipal de Angra do Heroismo');
insert into meio values (60, 'Policia Municipal de Terras de Bouro');
insert into meio values (90, 'Bombeiros de Abrantes');
insert into meio values (22, 'Policia Municipal de Sabugal');
insert into meio values (72, 'Policia Municipal de Mertola');
insert into meio values (8, 'Bombeiros de Murca');
insert into meio values (45, 'Policia Municipal de Nazare');
insert into meio values (83, 'Bombeiros de Aljustrel');
insert into meio values (30, 'Bombeiros de Mesao Frio');
insert into meio values (26, 'Policia Municipal de Vila Flor');
insert into meio values (80, 'Bombeiros de Olhao');
insert into meio values (71, 'Policia Municipal de Seia');
insert into meio values (19, 'Policia Municipal de Santo Tirso');
insert into meio values (71, 'Bombeiros de Paredes');
insert into meio values (43, 'Bombeiros de Fundao');
insert into meio values (20, 'Bombeiros de Mogadouro');
insert into meio values (82, 'Bombeiros de Camara de Lobos');
insert into meio values (96, 'Bombeiros de Santa Marta de Penaguiao');
insert into meio values (85, 'Bombeiros de Santa Cruz');
insert into meio values (60, 'Policia Municipal de Portel');
