insert into vigia values ('Oliveira do Hospital', 12);
insert into vigia values ('Monchique', 75);
insert into vigia values ('Sao Pedro do Sul', 54);
insert into vigia values ('Castro Daire', 49);
insert into vigia values ('Vila Verde', 34);
insert into vigia values ('Amares', 92);
insert into vigia values ('Ferreira do Alentejo', 37);
insert into vigia values ('Santarem', 16);
insert into vigia values ('Caldas da Rainha', 7);
insert into vigia values ('Vila Real', 10);
insert into vigia values ('Boticas', 64);
insert into vigia values ('Velas', 37);
insert into vigia values ('Celorico de Basto', 4);
insert into vigia values ('Almada', 57);
insert into vigia values ('Mira', 68);
insert into vigia values ('Vila Nova de Famalicao', 1);
insert into vigia values ('Nisa', 97);
insert into vigia values ('Viana do Castelo', 70);
insert into vigia values ('Felgueiras', 99);
insert into vigia values ('Odemira', 39);
insert into vigia values ('Ourique', 95);
insert into vigia values ('Penela', 66);
insert into vigia values ('Vila Nova de Cerveira', 66);
insert into vigia values ('Agueda', 18);
insert into vigia values ('Marco de Canaveses', 32);
insert into vigia values ('Penedono', 53);
insert into vigia values ('Vila Nova de Paiva', 47);
insert into vigia values ('Sever do Vouga', 60);
insert into vigia values ('Loures', 10);
insert into vigia values ('Viana do Alentejo', 5);
insert into vigia values ('Vila Nova de Poiares', 78);
insert into vigia values ('Evora', 41);
insert into vigia values ('Alpiarca', 9);
insert into vigia values ('Lousada', 77);
insert into vigia values ('Campo Maior', 85);
insert into vigia values ('Vinhais', 35);
insert into vigia values ('Caminha', 47);
insert into vigia values ('Penafiel', 46);
insert into vigia values ('Penalva do Castelo', 71);
insert into vigia values ('Cabeceiras de Basto', 48);
insert into vigia values ('Cartaxo', 1);
insert into vigia values ('Aveiro', 25);
insert into vigia values ('Vila Real de Santo Antonio', 44);
insert into vigia values ('Espinho', 92);
insert into vigia values ('Coruche', 28);
insert into vigia values ('Tarouca', 91);
insert into vigia values ('Santa Marta de Penaguiao', 38);
insert into vigia values ('Sobral de Monte Agraco', 41);
insert into vigia values ('Golega', 8);
insert into vigia values ('Ansiao', 53);
insert into vigia values ('Beja', 62);
insert into vigia values ('Arruda dos Vinhos', 87);
insert into vigia values ('Vila Nova de Foz Coa', 33);
insert into vigia values ('Bombarral', 73);
insert into vigia values ('Matosinhos', 22);
insert into vigia values ('Cascais', 22);
insert into vigia values ('Figueira de Castelo Rodrigo', 21);
insert into vigia values ('Paredes', 60);
insert into vigia values ('Ribeira de Pena', 20);
insert into vigia values ('Serta', 50);
insert into vigia values ('Oliveira de Azemeis', 36);
insert into vigia values ('Miranda do Corvo', 69);
insert into vigia values ('Vila Velha de Rodao', 30);
insert into vigia values ('Arganil', 36);
insert into vigia values ('Arraiolos', 28);
insert into vigia values ('Vale de Cambra', 51);
insert into vigia values ('Vila do Bispo', 27);
insert into vigia values ('Loule', 80);
insert into vigia values ('Ponte da Barca', 14);
insert into vigia values ('Constancia', 67);
insert into vigia values ('Grandola', 37);
insert into vigia values ('Fronteira', 13);
insert into vigia values ('Sao Joao da Pesqueira', 2);
insert into vigia values ('Machico', 62);
insert into vigia values ('Povoacao', 55);
insert into vigia values ('Vila Nova de Gaia', 61);
insert into vigia values ('Figueira da Foz', 88);
insert into vigia values ('Alcobaca', 26);
insert into vigia values ('Oliveira de Frades', 95);
insert into vigia values ('Alter do Chao', 50);
insert into vigia values ('Freixo de Espada a Cinta', 87);
insert into vigia values ('Pedrogao Grande', 99);
insert into vigia values ('Vimioso', 44);
insert into vigia values ('Corvo', 73);
insert into vigia values ('Mourao', 9);
insert into vigia values ('Sao Bras de Alportel', 52);
insert into vigia values ('Azambuja', 23);
insert into vigia values ('Vizela', 32);
insert into vigia values ('Ilhavo', 48);
insert into vigia values ('Vidigueira', 67);
insert into vigia values ('Gois', 96);
insert into vigia values ('Carregal do Sal', 20);
insert into vigia values ('Angra do Heroismo', 15);
insert into vigia values ('Sao Vicente', 29);
insert into vigia values ('Madalena', 56);
insert into vigia values ('Carrazeda de Ansiaes', 15);
insert into vigia values ('Vila Franca de Xira', 65);
insert into vigia values ('Castelo Branco', 72);
insert into vigia values ('Valongo', 78);
insert into vigia values ('Anadia', 11);
insert into vigia values ('Leiria', 86);
insert into vigia values ('Sousel', 51);
insert into vigia values ('Almeida', 2);
insert into vigia values ('Soure', 52);
insert into vigia values ('Lagos', 30);
insert into vigia values ('Aguiar da Beira', 6);
insert into vigia values ('Santo Tirso', 58);
insert into vigia values ('Chamusca', 81);
insert into vigia values ('Alcacer do Sal', 43);
insert into vigia values ('Covilha', 100);
insert into vigia values ('Almodovar', 29);
insert into vigia values ('Mora', 93);
insert into vigia values ('Seixal', 15);
insert into vigia values ('Pombal', 38);
insert into vigia values ('Manteigas', 30);
insert into vigia values ('Alvito', 9);
insert into vigia values ('Castro Verde', 22);
insert into vigia values ('Portel', 23);
insert into vigia values ('Lajes das Flores', 86);
insert into vigia values ('Silves', 20);
insert into vigia values ('Cinfaes', 28);
insert into vigia values ('Macao', 26);
insert into vigia values ('Resende', 83);
insert into vigia values ('Alcanena', 5);
insert into vigia values ('Alcoutim', 81);
insert into vigia values ('Nordeste', 71);
insert into vigia values ('Mogadouro', 68);
insert into vigia values ('Oliveira do Bairro', 77);
insert into vigia values ('Mealhada', 36);
insert into vigia values ('Tabuaco', 45);
insert into vigia values ('Celorico da Beira', 76);
insert into vigia values ('Pacos de Ferreira', 40);
insert into vigia values ('Olhao', 13);
insert into vigia values ('Murca', 49);
insert into vigia values ('Castelo de Vide', 77);
insert into vigia values ('Torre de Moncorvo', 83);
insert into vigia values ('Mirandela', 34);
insert into vigia values ('Lamego', 43);
insert into vigia values ('Ponte de Lima', 58);
insert into vigia values ('Gouveia', 31);
insert into vigia values ('Miranda do Douro', 96);
insert into vigia values ('Moimenta da Beira', 90);
insert into vigia values ('Ferreira do Zezere', 19);
insert into vigia values ('Idanha-a-Nova', 65);
insert into vigia values ('Gaviao', 89);
insert into vigia values ('Alvaiazere', 25);
insert into vigia values ('Melgaco', 16);
insert into vigia values ('Vila Vicosa', 3);
